FROM ghcr.io/astral-sh/uv:alpine

WORKDIR /app

# Copy necessary local packages
COPY backend /app

RUN uv sync --frozen --no-cache --no-dev

EXPOSE 3000

CMD ["/app/.venv/bin/fastapi", "run", "src/main.py", "--host", "0.0.0.0", "--port", "3000", "--proxy-headers"]
