"""Remove origin columns

Revision ID: dfe953f88e66
Revises: dad3dd917a21
Create Date: 2026-03-09 22:38:52.984328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfe953f88e66'
down_revision: Union[str, Sequence[str], None] = 'dad3dd917a21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maps_metadata', 'origin_y')
    op.drop_column('maps_metadata', 'origin_x')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maps_metadata', sa.Column('origin_x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('maps_metadata', sa.Column('origin_y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
